---
title: "Highlights"

---
<br/>

## Achievements
- **Gold Medal in ML & Big Data Trade** - at BRICS Future Skills Challenge while representing India, 2022
- **Rank 36** - in Amazon ML Challenge out of 800+ teams, 2023
- **National Finalist at rank 5** - in the eYantra Robotics Competition organised by IIT Bombay, 2019

## Leadership and Volunteering
- **ML Team Lead** - At [Omdena](https://www.omdena.com/), 2024. Lead a team of 12 to spearhead an end-to-end LLM chatbot application for mental health analysis
- **Head, Robotics & Intelligent Systems** - At Developer Student Clubs BVP, 2020. Organised events and workshops to enhance technical knowledge and practical skills among students
- **Google Code-in Mentor** - for [Tensorflow](https://codein.withgoogle.com/archive/2019/organization/6265089057882112/), 2019. Mentored high-school students participating in Google's open-source  event
- **Volunteer, Photography & Design Team** - At [Amoli Trust](https://amolitrust.com/), 2019

## Examination Scores
- **All India Rank 1089 (99th percentile)** - in Graduate Aptitude Test in Engineering, GATE CSIT 2021