---
title: "HybridLSTM for NIFTY50 prediction using global indices and technical indicators"
date: "07/06/2021"
---

- Published in: 2021 12th International Conference on Computing Communication and Networking Technologies (ICCCNT)
- Publisher: IEEE

### Abstract:
The Indian stock market is a venue for investors to buy and sell shares and make profits during the trades. The forecasting of stock prices ahead of time can help investors to generate more profits. However, the fluctuation of stock prices depends on many factors that are difficult to track manually. In this research, we propose the use of the long short-term network architecture to do effective forecasting of the NIFTY50 stock price index. We propose a hybrid model which uses a combination of 20 technical indicators and 13 global indices as the input variables. We then compare the performance of three long short-term memory networks with different input variables i.e. technical indicators, global indices and the combination of both. The performance of the three models is evaluated using root mean squared error, mean absolute error and r-squared error.


### Publication Link: 
[HybridLSTM for NIFTY50 prediction using global indices and technical indicators](https://ieeexplore.ieee.org/document/9579732){target="_blank"}