---
title: "Siamese Neural Networks for Pandemic Detection Using Chest Radiographs"
date: "06/01/2022"
---

- Published in: International Journal on “Technical and Physical Problems of Engineering” (IJTPE)
- Publisher: International Organization of IOTPE

### Abstract:
The recent developments in the field of deep learning have enabled the efficient diagnosis of medical imaging for determining a broad set of diseases. To reduce the spread and impact of the pandemic (COVID virus), machine learning techniques can be used to diagnose and predict the disease using chest X-ray images. In this research, we present an approach using Siamese Convolutional Neural Network (SCNN) to classify chest x-ray images into four classes, namely pandemic, SevereCOVID, Pneumonia and Normal. We present a comparative study between the performance of our Siamese network and other pre-trained CNN architectures i.e. VGG-16 and ResNet50 in this research. The model performance is tested by merging two publicly available datasets: COVID-Chest-Xray dataset and Chest X-Ray Images (Pneumonia). We achieved an accuracy of 98% on Siamese ResNet50 which gives the best performance in contrast to 95% on VGG-16, 93% on ResNet50 and 96% on Siamese VGG-16.

### Publication Link: 
[Siamese Neural Networks for Pandemic Detection Using Chest Radiographs](https://www.iotpe.com/IJTPE/IJTPE-2022/IJTPE-Issue51-Vol14-No2-Jun2022/13-IJTPE-Issue51-Vol14-No2-Jun2022-pp104-110.pdf){target="_blank"}